version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: kube-health
    binary: kube-health
    goos:
      - linux
      - darwin
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/rhobs/kube-health/cmd.Version={{.Version}}
      - -X github.com/rhobs/kube-health/cmd.Commit={{.Commit}}
      - -X github.com/rhobs/kube-health/cmd.Date={{.Date}}

  - id: kube-health-monitor
    binary: kube-health-monitor
    goos:
      - linux
      - darwin
    ldflags:
      - -s -w
      - -X github.com/rhobs/kube-health/cmd.Version={{.Version}}
      - -X github.com/rhobs/kube-health/cmd.Commit={{.Commit}}
      - -X github.com/rhobs/kube-health/cmd.Date={{.Date}}

    main: ./cmd/monitor

archives:
  - id: kube-health
    formats: tar.gz
    builds: [kube-health]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .Binary }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
  - id: kube-health-monitor
    formats: tar.gz
    builds: [kube-health-monitor]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .Binary }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
